name: Check Diff Between Production and Staging
on: [push]
jobs:
  diff:
    runs-on: ubuntu-20.04
    env:
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-publishing
    outputs: 
      matrix: ${{ steps.diff.outputs.matrix }}
      matrix1: ${{ steps.diff.outputs.matrix1 }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: ./run.sh install
      
      - name: Compute diff matrix
        id: diff 
        shell: python
        run: |
          import json
          import os
          import sys
          
          diff=os.popen('./run.sh diff_list').readlines()
          diff=[d.replace('\n', '') for d in diff]          
          diff_json=json.dumps(diff)
          
          with open('datasets.json', 'w') as f:
            json.dump(diff, f)
            
          print(diff_json, file = sys.stdout)
          
      - name: get stdout
        run: |
          ls -l 
          echo ::set-output name=matrix::${{ steps.diff.outputs.stdout }}  
          echo ::set-output name=matrix1::$(cat datasets.json)
          
      - name: Print Matrix
        run: |
          echo "${{ steps.diff.outputs.matrix }}"
          echo "${{ steps.diff.outputs.matrix1 }}"

  test:
    needs: [diff]
    runs-on: ubuntu-20.04
    steps:
      - run: echo ${{ fromJSON(needs.diff.outputs.matrix) }}
      - run: echo ${{ needs.diff.outputs.matrix }}
      - run: printf "${{ fromJSON(needs.diff.outputs.matrix) }}"
      - run: printf "${{ needs.diff.outputs.matrix }}"
      - run: echo ${{ fromJSON(needs.diff.outputs.matrix1) }}
      - run: echo ${{ needs.diff.outputs.matrix1 }}
      - run: printf "${{ fromJSON(needs.diff.outputs.matrix1) }}"
      - run: printf "${{ needs.diff.outputs.matrix1 }}"

  notify:
    runs-on: ubuntu-20.04
    needs: [diff, test]
    env:
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-publishing
    strategy:
      matrix: 
        dataset: ${{ fromJSON(needs.diff.outputs.matrix) }}
    steps:
       - uses: actions/checkout@v2
         
       - name: Install Dependencies
         run: ./run.sh install
         
       - name: Test diff
         run: ./run.sh diff ${{ matrix.dataset }}
