name: Production Diff Staging
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */15 * *"
jobs:
  diff:
    runs-on: ubuntu-20.04
    env:
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-publishing
    outputs: 
      matrix: ${{ steps.diff.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Install Dependencies
        run: ./run.sh install
      
      - name: Compute diff matrix
        id: diff 
        shell: python
        run: |
          import json
          import os
          import os
          
          diff=os.popen('./run.sh diff_list').readlines()
          diff=[d.replace('\n', '') for d in diff]
          diff_json=json.dumps(json.dumps(diff))
          os.system('''echo "::set-output name=matrix::{}"'''.format(diff_json))
          
      - name: Print Matrix
        run: |
          echo ${{ steps.diff.outputs.matrix }}

  notify:
    runs-on: ubuntu-20.04
    needs: [diff]
    env:
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-publishing
    strategy:
      matrix: 
        dataset: ${{ fromJSON(needs.diff.outputs.matrix) }}
    steps:            
      - uses: actions/checkout@v2
         
      - name: Install Dependencies
        run: ./run.sh install
       
      - name: Random Sleep
        run:  sleep $[ ( $RANDOM % 10 )  + 1 ]s

      - uses: lee-dohm/select-matching-issues@v1.2.0
        name: Close old issues for a given dataset
        id: oldissues
        with: 
          query: 'label:${{ matrix.dataset }}'
          token: ${{ github.token }}

      - name: Close found issues
        run: cat ${{ steps.oldissues.outputs.path }} | xargs gh issue close
         
      - uses: actions/github-script@v3
        name: Create Issue to Publish
        with: 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const title = `[publish] ${{ matrix.dataset }}`;
            const body = `
            ## Difference Detected Between \`Production\` and \`Staging\` in the following dataset(s)
            ## Dataset(s)
            \`\`\`yml
            - ${{ matrix.dataset }}
            \`\`\`
            ## Next Steps: 
            If you have manually checked above files and they seem to be ok, comment \`[publish]\` under this issue. 
            This would allow github actions to move staging files to production. 
            Feel free to close this issue once it's all complete. Thanks!
            `;
            github.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              assignees: ["nnxka"],
              labels: ['publish', ${{ matrix.dataset }}]
            });
