name: Staging -> Production

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-22.04
    env:
      AWS_S3_ENDPOINT: ${{ secrets.DO_S3_ENDPOINT }}
      AWS_ACCESS_KEY_ID: ${{ secrets.DO_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.DO_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: edm-publishing
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      run: ./run.sh install

    - name: Run recipe
      run: ./run.sh publish dcp_address_points

    - name: Success Message
      if: success()
      uses: peter-evans/close-issue@v1
      with:
        issue-number: ${{ github.event.issue.number }}
        comment: |
          ## Publish Complete!

          ${{ steps.parsing.outputs.datasets }}

          *Published By: @${{ github.actor }}* for more details, check [here](https://github.com/NYCPlanning/edm-data-operations/actions/runs/${{ github.run_id }})
